# Generated by Django 3.1 on 2021-06-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('core', models.BooleanField()),
                ('amount_a', models.DecimalField(decimal_places=1, max_digits=12)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
