# Generated by Django 3.1 on 2021-07-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_public_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='public_address',
        ),
    ]
