# Generated by Django 3.1 on 2021-07-04 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_company_public_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='com_name',
            new_name='uni_num',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='amount_865',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='public_address',
            field=models.CharField(default=111, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='amount_a',
            field=models.DecimalField(decimal_places=1, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
