# Generated by Django 3.1 on 2021-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210704_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contract_address',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
