# Generated by Django 3.1 on 2021-07-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=1, max_digits=12)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField()),
                ('state', models.CharField(max_length=40)),
                ('receive_compamy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_comapny', to='core.company')),
                ('send_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_company', to='core.company')),
            ],
        ),
    ]
