# Generated by Django 3.1 on 2021-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_company_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_orders',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
