# Generated by Django 3.1 on 2021-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210707_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_orders',
            name='end_date',
            field=models.DateField(),
        ),
    ]
