# Generated by Django 3.1 on 2021-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210707_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_orders',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
