# Generated by Django 3.1 on 2021-07-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210711_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_orders',
            name='state',
            field=models.IntegerField(choices=[(1, '憑證未發出'), (2, '訂單準備中'), (3, '訂單已完成'), (4, '違約')], default=1),
        ),
    ]
