# Generated by Django 3.1 on 2021-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210711_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
