# Generated by Django 3.1.7 on 2021-07-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tokenb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenb',
            name='token_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
