# Generated by Django 3.1.7 on 2021-07-19 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tokenb',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
