# Generated by Django 3.1 on 2021-07-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_tokena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_orders',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
