# Generated by Django 3.1 on 2021-07-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210723_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_orders',
            name='already_loan',
        ),
        migrations.RemoveField(
            model_name='company_orders',
            name='already_transfer',
        ),
        migrations.AddField(
            model_name='tokenb',
            name='already_loan',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tokenb',
            name='already_transfer',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12),
        ),
    ]
