# Generated by Django 3.1 on 2021-07-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210723_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_orders',
            name='tokenB_balance',
        ),
        migrations.AddField(
            model_name='tokenb',
            name='tokenB_balance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='company_orders',
            name='state',
            field=models.IntegerField(choices=[(1, '憑證未發出'), (2, '訂單準備中'), (3, '訂單已完成'), (4, '違約'), (5, '未驗證'), (6, '已完成驗證')], default=1),
        ),
    ]
