# Generated by Django 3.1 on 2021-07-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210724_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_orders',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (11, '11%'), (12, '12%'), (13, '13%')], null=True),
        ),
    ]
