# Generated by Django 3.1 on 2021-07-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210724_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_orders',
            name='state',
            field=models.IntegerField(choices=[(1, '憑證未發出'), (2, '訂單準備中'), (3, '訂單已完成'), (4, '違約'), (5, '未驗證'), (6, '完成驗證')], default=1),
        ),
        migrations.AlterField(
            model_name='tokenb',
            name='class_type',
            field=models.IntegerField(blank=True, choices=[(1, '應收'), (2, '訂單'), (3, '移轉'), (4, '貸款'), (5, '驗證抵押')], null=True),
        ),
    ]
