# Generated by Django 3.1 on 2021-07-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210725_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_orders',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
