# Generated by Django 3.1 on 2021-07-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210724_1446'),
        ('core', '0033_auto_20210725_0616'),
    ]

    operations = [
    ]
