# Generated by Django 3.1 on 2021-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20210725_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_orders',
            name='state',
            field=models.IntegerField(choices=[(1, '憑證未發出'), (2, '訂單準備中'), (3, '訂單已完成'), (4, '違約'), (5, '未驗證'), (6, '完成驗證'), (7, '尚未付款'), (8, '發出應付'), (9, '帳款已結清')], default=1),
        ),
    ]
