# Generated by Django 3.1.7 on 2021-07-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210725_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('principle', models.IntegerField(blank=True, null=True)),
                ('interest', models.IntegerField(blank=True, null=True)),
                ('date_span', models.IntegerField(blank=True, null=True)),
                ('riskClass', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], null=True)),
                ('transactionHash', models.CharField(blank=True, max_length=66, null=True)),
                ('loan_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_company', to='core.company')),
            ],
        ),
    ]
