# Generated by Django 3.1.7 on 2021-07-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_loancertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_orders',
            name='class_type',
            field=models.IntegerField(blank=True, choices=[(1, '應收'), (2, '訂單'), (3, '存貨')], null=True),
        ),
    ]
