# Generated by Django 3.1.7 on 2021-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_company_orders_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancertificate',
            name='curr_span',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_orders',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(6, '6%'), (8, '8%'), (10, '10%'), (12, '12%')], null=True),
        ),
    ]
