# Generated by Django 3.1.7 on 2021-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210731_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancertificate',
            name='avail_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tokenb',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, '融資中'), (2, '融資成功'), (3, '融資失敗'), (4, '融資結束'), (5, '違約')], null=True),
        ),
        migrations.AlterField(
            model_name='loancertificate',
            name='principle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
