# Generated by Django 3.1.7 on 2021-07-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210731_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('riskClass', models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('accu_earning', models.DecimalField(blank=True, decimal_places=18, default=0, max_digits=18)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='core.company')),
            ],
        ),
    ]
