# Generated by Django 3.1 on 2021-08-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210731_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancertificate',
            name='tokenB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_tokenB', to='core.tokenb'),
        ),
        migrations.AddField(
            model_name='tranche',
            name='loanCertificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_certificate', to='core.loancertificate'),
        ),
    ]
