# Generated by Django 3.1.7 on 2021-08-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210804_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_principle', models.TextField(blank=True, null=True)),
                ('term_interest', models.TextField(blank=True, null=True)),
                ('term', models.IntegerField(blank=True, null=True)),
                ('tokenB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_id', to='core.tokenb')),
            ],
        ),
    ]
