# Generated by Django 3.1.7 on 2021-08-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_company_image'),
        ('core', '0045_auto_20210810_0338'),
    ]

    operations = [
    ]
