# Generated by Django 3.1 on 2021-08-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_auto_20210810_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invest_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_address', models.CharField(max_length=42)),
                ('amount_865', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
