# Generated by Django 3.1.7 on 2021-08-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_invest_user'),
        ('core', '0047_auto_20210810_1415'),
    ]

    operations = [
    ]
