# Generated by Django 3.1 on 2021-08-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_acc_rec_auction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acc_rec_auction',
            new_name='Acc_rec_for_sale',
        ),
    ]
