# Generated by Django 3.1.7 on 2021-08-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_merge_20210818_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayable',
            name='term_interest',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='loanpayable',
            name='term_principle',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
    ]
