# Generated by Django 3.1 on 2021-08-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210821_0702'),
        ('core', '0047_auto_20210810_1415'),
    ]

    operations = [
    ]
