# Generated by Django 3.1.7 on 2021-08-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210818_0725'),
        ('core', '0051_merge_20210829_1151'),
    ]

    operations = [
    ]
