# Generated by Django 3.1.7 on 2021-08-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20210829_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenb',
            name='pmt',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loanpayable',
            name='term_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanpayable',
            name='term_principle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
