# Generated by Django 3.1.7 on 2021-08-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20210829_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payback_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('tokenB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payback_loan_id', to='core.tokenb')),
            ],
        ),
    ]
