# Generated by Django 3.1.7 on 2021-09-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_payback_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenb',
            name='pmt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
