# Generated by Django 3.1 on 2021-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_dividend_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranche',
            name='principle_left',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
