# Generated by Django 3.1 on 2021-09-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_tranche_principle_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranche',
            old_name='principle_left',
            new_name='principle_remain',
        ),
    ]
