# Generated by Django 3.1 on 2021-09-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20210906_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend_record',
            name='tranche',
        ),
        migrations.AddField(
            model_name='dividend_record',
            name='uni_tranche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividend_record', to='core.tranche'),
        ),
    ]
